source:
    host: "127.0.0.1"
    port: 3306
    driver: "mysql"
    username: "root"
    password: "root"
    database: "cleardb"
    disablelogger: true
destination:
    host: "localhost"
    port: 5432
    driver: "postgresql"
    username: "postgres"
    password: "postgres"
    database: "clear_dev"
    disablelogger: true
tables:
    -   old_name: "tbl_suspend_master"
        new_name: "suspend_master"
        migrate: true
        clone_source: false
        batch_size: 1000
        update_sequence: true
        skip_store_error: true
        truncate_destination: true
        mapping:
            work_item_id: "work_item_uid"
            reason_code: "reason_code"
            reason_description: "reason_description"
            require_note: "require_note"
            used_when: "used_when"
            trauma_only: "trauma_only"
            fac_only: "fac_only"
            provider_resolves: "provider_resolves"
            internal_use: "internal_use"
            created_at: "{{now()}}"
            updated_at: "{{now()}}"
            status: "{{'ACTIVE'}}"
            is_active: "{{true}}"