source:
    host: "127.0.0.1"
    port: 3306
    driver: "mysql"
    username: "root"
    password: "root"
    database: "cleardb"
    disablelogger: true
destination:
    host: "localhost"
    port: 5432
    driver: "postgresql"
    username: "postgres"
    password: "postgres"
    database: "clear20"
    disablelogger: true
tables:
    -   old_name: "tbl_user_type"
        new_name: "roles"
        migrate: true
        clone_source: false
        batch_size: 1000
        update_sequence: true
        skip_store_error: true
        truncate_destination: true
        mapping:
            role_id: "user_type_id"
            name: "user_description"
            slug: "{{slug(user_description)}}"
            is_active: "{{true}}"