source:
    host: "127.0.0.1"
    port: 3306
    driver: "mysql"
    username: "root"
    password: "root"
    database: "cleardb"
    disablelogger: true
destination:
    host: "localhost"
    port: 5432
    driver: "postgresql"
    username: "postgres"
    password: "postgres"
    database: "clear_dev"
    disablelogger: true
tables:
    -   old_name: "tbl_work_item"
        new_name: "work_item_settings"
        migrate: true
        keep_unmatched_fields: true
        exclude_fields:
            - "facility_id"
            - "work_item_type_id"
            - "work_item_uid"
        include_fields:
            - "work_item_id"
            - "is_active"
            - "status"
        extra_values:
            wi_setting_order_index: 1
        key_value_table: true
        store_data_type: true
        mapping:
            work_item_id: "work_item_uid"
            is_active: "{{true}}"
            status: "{{'ACTIVE'}}"