source:
    host: "localhost"
    port: 5432
    driver: "postgresql"
    username: "postgres"
    password: "postgres"
    database: "clear20"
    disablelogger: true
destination:
    host: "localhost"
    port: 5432
    driver: "postgresql"
    username: "postgres"
    password: "postgres"
    database: "clear20"
    disablelogger: true
tables:
    -   old_name: "tbl_user_type"
        new_name: "user_permissions"
        migrate: true
        clone_source: false
        batch_size: 1000
        query: "SELECT us.user_id, us.entity_id, us.role_id, us.company_id, us.service_id, ce.entity FROM( SELECT ua.user_uid as user_id, work_item_uid as entity_id, r.role_id,cs.company_id, cs.service_id, cs.company_service_id FROM tbl_user_access ua JOIN roles r ON ua.user_type_id = r.role_id JOIN company_roles cr ON cr.role_id = r.role_id JOIN company_services cs ON cs.company_service_id = cr.company_service_id) us JOIN company_entities ce ON ce.company_service_id = us.company_service_id AND us.entity_id = ce.entity_id ;"
        skip_store_error: true
        truncate_destination: true
        mapping:
            company_id: "company_id"
            service_id: "service_id"
            role_id: "role_id"
            user_id: "user_id"
            entity: "entity"
            entity_id: "entity_id"
            created_at: "{{now()}}"
            updated_at: "{{now()}}"
            status: "{{'ACTIVE'}}"
            is_active: "{{true}}"